teaching:
- title: Research Experiences for Undergraduates (REU) Mentor
  term: Summer 2023
  location: Rutgers University / DIMACS
  note: Along with my advisor Sepehr Assadi.
- title: Directed Reading Program (DRP) Mentor for Women in Mathematics (WiM)
  term: Winter 2024
  location: University of Waterloo
- title: Guest Lecture in Randomized Algorithms (CS 761)
  term: Winter 2025
  location: University of Waterloo
  link: https://sepehr.assadi.info/courses/cs761-w25/
- title: Guest Lectures on Sublinear and Streaming Algorithms
  term: "Summer 2020\u20132024"
  location: Program in Algorithmic and Combinatorial Thinking (PACT), Princeton University
- title: Teaching Assistant for Design and Analysis of Computer Algorithms (CS 344)
  term: Spring 2021, Spring 2022, Fall 2021
  location: Rutgers University
- title: Teaching Assistant for Introduction to Discrete Structures (CS 205)
  term: Fall 2020, Summer 2021
  location: Rutgers University
- title: Teaching Assistant for Discrete Mathematics
  term: Summer 2019
  location: Program in Algorithmic and Combinatorial Thinking (PACT), Princeton University
reviews:
- venue: Symposium on Theory of Computing (STOC)
  years: 2022, 2024, 2025
- venue: Symposium on Foundations of Computer Science (FOCS)
  years: '2025'
- venue: Symposium on Discrete Algorithms (SODA)
  years: 2022, 2023, 2024
- venue: Innovations in Theoretical Computer Science (ITCS)
  years: 2024, 2025
- venue: Symposium on Principles of Database Systems (PODS)
  years: '2025'
- venue: European Symposium on Algorithms (ESA)
  years: 2022, 2023, 2024
- venue: International Colloquium on Automata, Languages, and Programming (ICALP)
  years: 2023, 2025
- venue: Symposium on Principles of Distributed Computing (PODC)
  years: '2021'
